name: Build Pipeline

on:
  push:
    branches:
      - main
      - feature/*
    pull_request:
      branches:
        - main


jobs:
  test:
    steps:
      - name: test
        id: test
        run: |
          sleep 10