name: Build Pipeline

on:
  push:
    branches:
      - main
      - feature/*
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - name: Try to fail
        run: exit 1