name: Build Pipeline

on:
  push:
    branches:
      - main
      - feature/*
    pull_request:
      branches:
        - main

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - run: "sleep 10"

  test:
    runs-on: ubuntu-24.04
    needs: [setup]
    steps:
      - name: test
        id: test
        run: |
          exit 1

  results:
    if: success() || failure()
    runs-on: ubuntu-24.04
    needs: [setup, test]
    steps:
      - name: results
        run: |
          testResult="${{ needs.test.result }}"
          if [[ $testResult == "success" ]]; then
            exit 0
          else
            exit 1
          fi

